server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_rest
    username: myUser
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: false
  liquibase:
    enabled: true
    change-log: classpath:db/migration/changelog-master.yaml

jwt:
  secret: #$JWT0156
  expiration: 1800000

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled:
      enabled: false